AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    orders-api

    SAM Template for simple api.


Globals:
    Function:
        Runtime: python3.9
        Environment:
            Variables:
                ORDERS_TABLE: !Ref OrdersTable

Resources:
    CreateOrderFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: orders-api/
            Handler: create.lambda_handler
            Events:
                CreateOrders:
                    Type: Api
                    Properties:
                        Path: /orders
                        Method: POST
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref OrdersTable

    ReadOrderFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: orders-api/
            Handler: read.lambda_handler
            Events:
                ReadOrders:
                    Type: Api
                    Properties:
                        Path: /orders/{id}
                        Method: GET
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref OrdersTable

    OrdersTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey:
                Name: id
                Type: Number

Outputs:
    CreateOrdersAPI:
        Description: "API Endpoint"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
    TestGetRequest:
        Value: !Sub "curl https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders/1"
    CreateOrderLambdaARN:
        Description: "Add order lambda ARN"
        Value: !GetAtt CreateOrderFunction.Arn
    CreateOrderLambdaIamRoleArn:
        Description: "Add order lambda IAM Role ARN"
        Value: !GetAtt CreateOrderFunctionRole.Arn